// Hyperlipidemia - surveillance Related observations: lipid panel
// "Measure total cholesterol and HDL every six months in patients taking statins to ensure compliance. "

// Basis:

/*
NOTE: This example is for instructional purposes only and is derived from work in progress.
It should in no way be considered a final specification or recommendation for guidance.
*/

library Hyperlipidemia-surveillance

using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers
// include cqf.fhir.common.FHIRCommon // uncomment as needed
