// Herpes zoster immunization (Zostavax) Related observations: Zostavax
// "Single dose of vaccine for adults aged >60 y"

// Basis:

/*
NOTE: This example is for instructional purposes only and is derived from work in progress.
It should in no way be considered a final specification or recommendation for guidance.
*/

library live-zoster-vaccine

using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers
// include cqf.fhir.common.FHIRCommon // uncomment as needed
