// Vascular disease - monitor lipids Related observations: lipid panel
// "Check lipid panel every 6 months in all patients with vascular disease (ischemic heart disease, stroke or peripheral vascular disease). "

// Basis:

/*
NOTE: This example is for instructional purposes only and is derived from work in progress.
It should in no way be considered a final specification or recommendation for guidance.
*/

library liver-disease-LFT-surveillance

using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers
// include cqf.fhir.common.FHIRCommon // uncomment as needed
