// Folic acid chemoprevention Related observations: folate assessment
// "Women planning or capable of pregnancy should take a daily supplement with 0.4-0.8 mg of folic acid. "

// Basis:

/*
NOTE: This example is for instructional purposes only and is derived from work in progress.
It should in no way be considered a final specification or recommendation for guidance.
*/

library FolateChemoprevention

using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers
// include cqf.fhir.common.FHIRCommon // uncomment as needed
