// Senior PPSV23 Related observations: Pneumovax
// "Immunize adults aged >=65 y against pneumococcal disease with PPSV23. "

// Basis:

/*
NOTE: This example is for instructional purposes only and is derived from work in progress.
It should in no way be considered a final specification or recommendation for guidance.
*/

library Ppsv23VaccineAge

using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers
// include cqf.fhir.common.FHIRCommon // uncomment as needed
