// Diabetes - statin intensity assessment Related observations: statin assessment
// "Reassess statin intensty in all patients with diabetes age 40-79 every 6 months based on current lipid values. "

// Basis:

/*
NOTE: This example is for instructional purposes only and is derived from work in progress.
It should in no way be considered a final specification or recommendation for guidance.
*/

library AdaStatinIntensity

using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers
// include cqf.fhir.common.FHIRCommon // uncomment as needed
