// Gonorrhea screening Related observations: gonorrhea PCR
// "Screen for gonorrhea in sexually active women aged 16-24 years. "

// Basis:

/*
NOTE: This example is for instructional purposes only and is derived from work in progress.
It should in no way be considered a final specification or recommendation for guidance.
*/

library GonorrheaScreening

using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers
// include cqf.fhir.common.FHIRCommon // uncomment as needed
