// Syphilis screening Related observations: RPR
// "Screen all persons at increased risk for syphilis infection. "

// Basis:

/*
NOTE: This example is for instructional purposes only and is derived from work in progress.
It should in no way be considered a final specification or recommendation for guidance.
*/

library SyphilisScreening

using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers
// include cqf.fhir.common.FHIRCommon // uncomment as needed
