// PPSV23 - splenectomy Related observations: Pneumovax
// "PPSV23 vaccine for all patients with history of splenectomy"

// Basis:

/*
NOTE: This example is for instructional purposes only and is derived from work in progress.
It should in no way be considered a final specification or recommendation for guidance.
*/

library Ppsv23Splenectomy

using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers
// include cqf.fhir.common.FHIRCommon // uncomment as needed
