// PPSV23 - tobacco smokers Related observations: Pneumovax
// "PPSV23 immunzation for smokers age 19-64"

// Basis:

/*
NOTE: This example is for instructional purposes only and is derived from work in progress.
It should in no way be considered a final specification or recommendation for guidance.
*/

library Ppsv23Smoker

using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers
// include cqf.fhir.common.FHIRCommon // uncomment as needed
